openapi: 3.0.0
info:
  version: 1.0.0
  title: Employee API
paths:
  "/employee/{id}":
    get:
      tags:
        - "社員情報API"
      summary:
        "指定したデータを取得"
      description:
        "指定したIDの社員を検索し、情報を取得します。"
      parameters:
        - name: "id"
          in: "path"
          description: "社員を特定する一意のID"
          required: true
          type: "integer"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  name:
                    type: "string"
                  mail:
                    type: "string"
                example:
                  no: 1
                  name: "横山　春雄"
                  type: "haruo.com"
  "/employee":
    get:
      tags:
        - "社員情報API"
      summary:
        "全データを取得"
      description:
        "DB内の全てのデータを取得します"

      responses:
          200:
            description: "Success"
            content:
              application/json:
                schema:
#                  type: "object"
#                  properties:
#                    id:
#                      type: "integer"
#                    name:
#                      type: "string"
#                    mail:
#                      type: "string"
#                  example:
#                    no: 1
#                    name: "横山　春雄"
#                    type: "haruo.com"








